-- MySQL / MariaDB schema for the Manav Narula Realtor website (Hostinger).
-- Generated by scripts/export-mysql.mjs on 2026-10-04T09:12:50.924Z from the live PostgreSQL database.
-- Import this first, then data.sql. Times are stored in UTC.
SET NAMES utf8mb4;
SET time_zone = '+00:00';
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `audit_log`;
CREATE TABLE `audit_log` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL,
  `action` LONGTEXT NOT NULL,
  `entity` LONGTEXT NOT NULL,
  `entity_id` LONGTEXT NULL,
  `details` JSON NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  CONSTRAINT `audit_log_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  KEY `audit_log_created_idx` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `banners`;
CREATE TABLE `banners` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `group` LONGTEXT NOT NULL DEFAULT ('carousel'),
  `image` LONGTEXT NULL,
  `headline` LONGTEXT NOT NULL,
  `line` LONGTEXT NULL,
  `cta_label` LONGTEXT NULL,
  `cta_href` LONGTEXT NULL,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  `start_date` DATE NULL,
  `end_date` DATE NULL,
  `sort_order` INT NOT NULL DEFAULT 0,
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `blog_posts`;
CREATE TABLE `blog_posts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `slug` VARCHAR(255) NOT NULL,
  `title` LONGTEXT NOT NULL,
  `category` LONGTEXT NULL,
  `author` LONGTEXT NULL,
  `cover` LONGTEXT NULL,
  `excerpt` LONGTEXT NULL,
  `body` LONGTEXT NOT NULL DEFAULT (''),
  `meta_title` LONGTEXT NULL,
  `meta_description` LONGTEXT NULL,
  `status` LONGTEXT NOT NULL DEFAULT ('Draft'),
  `published_at` DATETIME(6) NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `blog_posts_slug_key` (`slug`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `campaign_messages`;
CREATE TABLE `campaign_messages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `campaign_id` INT NOT NULL,
  `lead_id` INT NULL,
  `prospect_id` INT NULL,
  `phone` LONGTEXT NOT NULL,
  `name` LONGTEXT NULL,
  `body` LONGTEXT NULL,
  `status` LONGTEXT NOT NULL DEFAULT ('Queued'),
  `provider_id` LONGTEXT NULL,
  `error` LONGTEXT NULL,
  `sent_at` DATETIME(6) NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT `campaign_messages_campaign_id_fkey` FOREIGN KEY (`campaign_id`) REFERENCES `campaigns` (`id`) ON DELETE CASCADE,
  CONSTRAINT `campaign_messages_lead_id_fkey` FOREIGN KEY (`lead_id`) REFERENCES `leads` (`id`) ON DELETE SET NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `campaign_messages_prospect_id_fkey` FOREIGN KEY (`prospect_id`) REFERENCES `prospects` (`id`) ON DELETE SET NULL,
  KEY `campaign_messages_campaign_idx` (`campaign_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `campaign_templates`;
CREATE TABLE `campaign_templates` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` LONGTEXT NOT NULL,
  `message` LONGTEXT NOT NULL DEFAULT (''),
  `variants` JSON NOT NULL DEFAULT ('[]'),
  `message_type` LONGTEXT NOT NULL DEFAULT ('text'),
  `template_name` LONGTEXT NULL,
  `template_language` LONGTEXT NOT NULL DEFAULT ('en'),
  `media_type` LONGTEXT NOT NULL DEFAULT ('none'),
  `media_url` LONGTEXT NULL,
  `media_filename` LONGTEXT NULL,
  `created_by` INT NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT `campaign_templates_created_by_fkey` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `campaigns`;
CREATE TABLE `campaigns` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` LONGTEXT NOT NULL,
  `message` LONGTEXT NOT NULL DEFAULT (''),
  `message_type` LONGTEXT NOT NULL DEFAULT ('text'),
  `template_name` LONGTEXT NULL,
  `template_language` LONGTEXT NOT NULL DEFAULT ('en'),
  `audience` JSON NOT NULL DEFAULT ('{}'),
  `status` LONGTEXT NOT NULL DEFAULT ('Draft'),
  `scheduled_at` DATETIME(6) NULL,
  `started_at` DATETIME(6) NULL,
  `sent_at` DATETIME(6) NULL,
  `total` INT NOT NULL DEFAULT 0,
  `sent_count` INT NOT NULL DEFAULT 0,
  `failed_count` INT NOT NULL DEFAULT 0,
  `skipped_count` INT NOT NULL DEFAULT 0,
  `created_by` INT NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `media_type` LONGTEXT NOT NULL DEFAULT ('none'),
  `media_url` LONGTEXT NULL,
  `media_filename` LONGTEXT NULL,
  `variants` JSON NOT NULL DEFAULT ('[]'),
  `window_start` INT NOT NULL DEFAULT 10,
  `window_end` INT NOT NULL DEFAULT 19,
  `daily_cap` INT NOT NULL DEFAULT 200,
  `gap_seconds` INT NOT NULL DEFAULT 3,
  CONSTRAINT `campaigns_created_by_fkey` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `lead_activities`;
CREATE TABLE `lead_activities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lead_id` INT NULL,
  `prospect_id` INT NULL,
  `user_id` INT NULL,
  `type` LONGTEXT NOT NULL,
  `body` LONGTEXT NULL,
  `from_status` LONGTEXT NULL,
  `to_status` LONGTEXT NULL,
  `scheduled_at` DATETIME(6) NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT `lead_activities_lead_id_fkey` FOREIGN KEY (`lead_id`) REFERENCES `leads` (`id`) ON DELETE CASCADE,
  PRIMARY KEY (`id`),
  CONSTRAINT `lead_activities_prospect_id_fkey` FOREIGN KEY (`prospect_id`) REFERENCES `prospects` (`id`) ON DELETE CASCADE,
  CONSTRAINT `lead_activities_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  KEY `lead_activities_lead_idx` (`lead_id`),
  KEY `lead_activities_prospect_idx` (`prospect_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `lead_sources`;
CREATE TABLE `lead_sources` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  UNIQUE KEY `lead_sources_name_key` (`name`),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `leads`;
CREATE TABLE `leads` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` LONGTEXT NOT NULL,
  `phone` VARCHAR(255) NOT NULL,
  `email` LONGTEXT NULL,
  `interest` LONGTEXT NULL,
  `budget` LONGTEXT NULL,
  `locality` LONGTEXT NULL,
  `property_id` INT NULL,
  `project_id` INT NULL,
  `source` LONGTEXT NOT NULL DEFAULT ('Website'),
  `status` LONGTEXT NOT NULL DEFAULT ('New'),
  `assigned_to` INT NULL,
  `created_by` INT NULL,
  `notes` LONGTEXT NULL,
  `tags` JSON NOT NULL DEFAULT ('[]'),
  `whatsapp_opt_in` TINYINT(1) NOT NULL DEFAULT 1,
  `next_follow_up_at` DATETIME(6) NULL,
  `last_activity_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT `leads_assigned_to_fkey` FOREIGN KEY (`assigned_to`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `leads_created_by_fkey` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `leads_project_id_fkey` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`) ON DELETE SET NULL,
  CONSTRAINT `leads_property_id_fkey` FOREIGN KEY (`property_id`) REFERENCES `properties` (`id`) ON DELETE SET NULL,
  KEY `leads_phone_idx` (`phone`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `localities`;
CREATE TABLE `localities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `sort_order` INT NOT NULL DEFAULT 0,
  `zone` LONGTEXT NOT NULL DEFAULT ('Central'),
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  UNIQUE KEY `localities_name_key` (`name`),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `media`;
CREATE TABLE `media` (
  `name` VARCHAR(255) NOT NULL,
  `content_type` LONGTEXT NOT NULL,
  `size` INT NOT NULL,
  `data` LONGBLOB NOT NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `offers`;
CREATE TABLE `offers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` LONGTEXT NOT NULL,
  `image` LONGTEXT NULL,
  `text` LONGTEXT NULL,
  `link` LONGTEXT NULL,
  `property_id` INT NULL,
  `project_id` INT NULL,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  `start_date` DATE NULL,
  `end_date` DATE NULL,
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  CONSTRAINT `offers_project_id_fkey` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`) ON DELETE SET NULL,
  CONSTRAINT `offers_property_id_fkey` FOREIGN KEY (`property_id`) REFERENCES `properties` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `page_videos`;
CREATE TABLE `page_videos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `page_key` VARCHAR(255) NOT NULL DEFAULT 'home_loans',
  `youtube_id` LONGTEXT NOT NULL,
  `title` LONGTEXT NULL,
  `sort_order` INT NOT NULL DEFAULT 0,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  KEY `page_videos_page_idx` (`page_key`, `sort_order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `partner_banks`;
CREATE TABLE `partner_banks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` LONGTEXT NOT NULL,
  `logo_url` LONGTEXT NULL,
  `tagline` LONGTEXT NULL,
  `sort_order` INT NOT NULL DEFAULT 0,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `popups`;
CREATE TABLE `popups` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `kind` LONGTEXT NOT NULL DEFAULT ('promo'),
  `title` LONGTEXT NOT NULL,
  `text` LONGTEXT NULL,
  `image` LONGTEXT NULL,
  `cta_label` LONGTEXT NULL,
  `cta_href` LONGTEXT NULL,
  `pages` LONGTEXT NOT NULL DEFAULT ('all'),
  `delay_seconds` INT NOT NULL DEFAULT 8,
  `start_date` DATE NULL,
  `end_date` DATE NULL,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT `popups_kind_check` CHECK (`kind` IN ('promo', 'consultation')),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `project_configurations`;
CREATE TABLE `project_configurations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `project_id` INT NOT NULL,
  `type` LONGTEXT NOT NULL,
  `area` LONGTEXT NULL,
  `price` LONGTEXT NULL,
  `sort_order` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  CONSTRAINT `project_configurations_project_id_fkey` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `project_milestones`;
CREATE TABLE `project_milestones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `project_id` INT NOT NULL,
  `title` LONGTEXT NOT NULL,
  `date` DATE NULL,
  `done` TINYINT(1) NOT NULL DEFAULT 0,
  `sort_order` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  CONSTRAINT `project_milestones_project_id_fkey` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `projects`;
CREATE TABLE `projects` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `slug` VARCHAR(255) NOT NULL,
  `name` LONGTEXT NOT NULL,
  `developer` LONGTEXT NULL,
  `locality` LONGTEXT NULL,
  `status` LONGTEXT NOT NULL DEFAULT ('Upcoming'),
  `image` LONGTEXT NULL,
  `gallery` JSON NOT NULL DEFAULT ('[]'),
  `starting_price` LONGTEXT NULL,
  `possession` LONGTEXT NULL,
  `key_facts` JSON NOT NULL DEFAULT ('[]'),
  `amenities` JSON NOT NULL DEFAULT ('[]'),
  `rera` LONGTEXT NULL,
  `description` LONGTEXT NULL,
  `brochure` LONGTEXT NULL,
  `master_plan` LONGTEXT NULL,
  `floor_plan` LONGTEXT NULL,
  `published` TINYINT(1) NOT NULL DEFAULT 0,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `projects_slug_key` (`slug`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `properties`;
CREATE TABLE `properties` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `slug` VARCHAR(255) NOT NULL,
  `title` LONGTEXT NOT NULL,
  `type` LONGTEXT NOT NULL,
  `purpose` LONGTEXT NOT NULL DEFAULT ('Buy'),
  `locality` LONGTEXT NULL,
  `project_id` INT NULL,
  `price` BIGINT NOT NULL DEFAULT 0,
  `bhk` INT NULL,
  `baths` INT NULL,
  `area` DECIMAL(20,4) NULL,
  `area_unit` LONGTEXT NOT NULL DEFAULT ('sq.ft'),
  `super_area` DECIMAL(20,4) NULL,
  `floor` LONGTEXT NULL,
  `facing` LONGTEXT NULL,
  `furnishing` LONGTEXT NULL,
  `parking` LONGTEXT NULL,
  `possession` LONGTEXT NULL,
  `status` LONGTEXT NOT NULL DEFAULT ('Ready'),
  `description` LONGTEXT NULL,
  `long_description` LONGTEXT NULL,
  `amenities` JSON NOT NULL DEFAULT ('[]'),
  `trust` JSON NOT NULL DEFAULT ('[]'),
  `rera` LONGTEXT NULL,
  `nearby` JSON NOT NULL DEFAULT ('[]'),
  `featured` TINYINT(1) NOT NULL DEFAULT 0,
  `published` TINYINT(1) NOT NULL DEFAULT 0,
  `meta_title` LONGTEXT NULL,
  `meta_description` LONGTEXT NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `address_line` LONGTEXT NULL,
  `street` LONGTEXT NULL,
  `city` LONGTEXT NOT NULL DEFAULT ('Jalandhar'),
  `pincode` LONGTEXT NULL,
  `maps_url` LONGTEXT NULL,
  `master_plan` LONGTEXT NULL,
  `floor_plan` LONGTEXT NULL,
  `floor_plans` JSON NOT NULL DEFAULT ('[]'),
  PRIMARY KEY (`id`),
  CONSTRAINT `properties_project_id_fkey` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`) ON DELETE SET NULL,
  UNIQUE KEY `properties_slug_key` (`slug`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `property_images`;
CREATE TABLE `property_images` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `property_id` INT NOT NULL,
  `url` LONGTEXT NOT NULL,
  `sort_order` INT NOT NULL DEFAULT 0,
  `is_cover` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  CONSTRAINT `property_images_property_id_fkey` FOREIGN KEY (`property_id`) REFERENCES `properties` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `prospects`;
CREATE TABLE `prospects` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` LONGTEXT NOT NULL,
  `phone` VARCHAR(255) NOT NULL,
  `email` LONGTEXT NULL,
  `locality` LONGTEXT NULL,
  `budget` LONGTEXT NULL,
  `interest` LONGTEXT NULL,
  `source` LONGTEXT NOT NULL DEFAULT ('Data entry'),
  `tags` JSON NOT NULL DEFAULT ('[]'),
  `status` LONGTEXT NOT NULL DEFAULT ('New'),
  `assigned_to` INT NULL,
  `added_by` INT NULL,
  `whatsapp_opt_in` TINYINT(1) NOT NULL DEFAULT 0,
  `notes` LONGTEXT NULL,
  `last_contacted_at` DATETIME(6) NULL,
  `next_follow_up_at` DATETIME(6) NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT `prospects_added_by_fkey` FOREIGN KEY (`added_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `prospects_assigned_to_fkey` FOREIGN KEY (`assigned_to`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  UNIQUE KEY `prospects_phone_key` (`phone`),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `sales`;
CREATE TABLE `sales` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sale_date` DATE NOT NULL,
  `lead_id` INT NULL,
  `prospect_id` INT NULL,
  `property_id` INT NULL,
  `property_title` LONGTEXT NULL,
  `client_name` LONGTEXT NULL,
  `deal_value` BIGINT NOT NULL DEFAULT 0,
  `commission` BIGINT NOT NULL DEFAULT 0,
  `employee_id` INT NULL,
  `notes` LONGTEXT NULL,
  `document_url` LONGTEXT NULL,
  `status` LONGTEXT NOT NULL DEFAULT ('Pending approval'),
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT `sales_employee_id_fkey` FOREIGN KEY (`employee_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `sales_lead_id_fkey` FOREIGN KEY (`lead_id`) REFERENCES `leads` (`id`) ON DELETE SET NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `sales_property_id_fkey` FOREIGN KEY (`property_id`) REFERENCES `properties` (`id`) ON DELETE SET NULL,
  CONSTRAINT `sales_prospect_id_fkey` FOREIGN KEY (`prospect_id`) REFERENCES `prospects` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `schema_migrations`;
CREATE TABLE `schema_migrations` (
  `name` VARCHAR(255) NOT NULL,
  `applied_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `settings`;
CREATE TABLE `settings` (
  `key` VARCHAR(255) NOT NULL,
  `value` JSON NOT NULL,
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `tags`;
CREATE TABLE `tags` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  UNIQUE KEY `tags_name_key` (`name`),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `task_comments`;
CREATE TABLE `task_comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `task_id` INT NOT NULL,
  `user_id` INT NULL,
  `body` LONGTEXT NOT NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  CONSTRAINT `task_comments_task_id_fkey` FOREIGN KEY (`task_id`) REFERENCES `tasks` (`id`) ON DELETE CASCADE,
  CONSTRAINT `task_comments_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `task_records`;
CREATE TABLE `task_records` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `task_id` INT NOT NULL,
  `lead_id` INT NULL,
  `prospect_id` INT NULL,
  CONSTRAINT `task_records_lead_id_fkey` FOREIGN KEY (`lead_id`) REFERENCES `leads` (`id`) ON DELETE CASCADE,
  PRIMARY KEY (`id`),
  CONSTRAINT `task_records_prospect_id_fkey` FOREIGN KEY (`prospect_id`) REFERENCES `prospects` (`id`) ON DELETE CASCADE,
  CONSTRAINT `task_records_task_id_fkey` FOREIGN KEY (`task_id`) REFERENCES `tasks` (`id`) ON DELETE CASCADE,
  KEY `task_records_task_idx` (`task_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `tasks`;
CREATE TABLE `tasks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` LONGTEXT NOT NULL,
  `description` LONGTEXT NULL,
  `lead_id` INT NULL,
  `prospect_id` INT NULL,
  `assigned_to` INT NULL,
  `created_by` INT NULL,
  `due_date` DATE NULL,
  `priority` LONGTEXT NOT NULL DEFAULT ('normal'),
  `status` LONGTEXT NOT NULL DEFAULT ('Open'),
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT `tasks_assigned_to_fkey` FOREIGN KEY (`assigned_to`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `tasks_created_by_fkey` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `tasks_lead_id_fkey` FOREIGN KEY (`lead_id`) REFERENCES `leads` (`id`) ON DELETE SET NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `tasks_priority_check` CHECK (`priority` IN ('normal', 'high')),
  CONSTRAINT `tasks_prospect_id_fkey` FOREIGN KEY (`prospect_id`) REFERENCES `prospects` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` LONGTEXT NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `phone` LONGTEXT NULL,
  `role` LONGTEXT NOT NULL DEFAULT ('employee'),
  `status` LONGTEXT NOT NULL DEFAULT ('active'),
  `password_hash` LONGTEXT NOT NULL,
  `must_reset` TINYINT(1) NOT NULL DEFAULT 0,
  `last_login_at` DATETIME(6) NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  UNIQUE KEY `users_email_key` (`email`),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


SET FOREIGN_KEY_CHECKS = 1;
